@startuml

actor 管理员


管理员 --> 管理后台 : 封禁用户
管理后台 -> 暖聊 : 调用封禁接口
actor 用户
暖聊 -> 用户 : 强制用户退出登陆
用户 -> 暖聊 : 登陆暖聊
暖聊 -> lanling : 检查用户封禁状态 如果处于封禁状态弹出 申诉h5

alt 未申诉
    用户 -> 暖聊 : 申诉页面

else 申诉进行中
    用户 -> 暖聊 : 申诉进行中页面
    
else 申诉过并且审核已失败
    用户 -> 暖聊 : 申诉失败页面
end

@enduml

